# Generated by Django 4.1.5 on 2023-01-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_todo_project_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
